### ISSUE TITLE
Move website to GitHub pages + Cloudflare (CDN + SSL)

### ISSUE THREAD

**Issue by lmammino** [fastify/website-metalsmith#26]
We are currently hosting the website on S3, which is not an ideal solution for several reasons:

  1. It's a paid service
  2. complex deployment process
  3. No SSL (unless combined with CloudFront or some other CDN/SSL service)

The TODO list to get this done is the following:

  - [x] Activate deploy on GitHub pages #25 
  - [x] Reconfigure main NS DNS records as in the table below (mostly for @mcollina)

Current Nameservers | Change Nameservers to:
-- | --
c.dns.gandi.net | gordon.ns.cloudflare.com
b.dns.gandi.net | meg.ns.cloudflare.com
a.dns.gandi.net | **Remove**

  - [x] Wait for DNS propagation (best if 24hrs)
  - [x] Check if Clouflare detected the DNS propagation and activated the API access (for @lmammino)
  - [x] Add CDN invalidation on deploy through cloudflare APIs (#27)
  - [x] Remove old deployment to S3 (#28)

Important Note: **The switch shouldn't generate any downtime**

**Comment by lmammino** [comment]
@mcollina, @delvedor, @allevo et Al., 
I created a PR for every step that involves code changes (see description in this issue).

Let me know if you are happy with this and when you are ready to proceed.

**Comment by mcollina** [comment]
I have landed #25 and rerouted the DNS servers.

**Comment by lmammino** [comment]
Great job @mcollina. I should get an email when Cloudflare picks up the new dns and be back able to move things forward by myself
